package com.aim.questionnaire.dao;

import com.aim.questionnaire.dao.entity.AutoAnswerEntity;
import com.aim.questionnaire.dao.entity.AutoAnswerEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface AutoAnswerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    long countByExample(AutoAnswerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int deleteByExample(AutoAnswerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int insert(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int insertSelective(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    List<AutoAnswerEntity> selectByExample(AutoAnswerEntityExample example);

    List<AutoAnswerEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    AutoAnswerEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AutoAnswerEntity record, @Param("example") AutoAnswerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AutoAnswerEntity record, @Param("example") AutoAnswerEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AutoAnswerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AutoAnswerEntity record);
}